### ISSUE TITLE
Handle no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by filipvanlaenen** [filipvanlaenen/sharpen_pitest#10]
```
/home/fvl/bin/sharpen_pitest.rb:128:in `rjust': no implicit conversion from nil to integer (TypeError)
	from /home/fvl/bin/sharpen_pitest.rb:128:in `<main>'
```

**Comment by filipvanlaenen** [comment]
This seems to occur when test coverage is 100%.
