### ISSUE TITLE
Catch missing test classes gracefully

### ISSUE THREAD

**Issue by filipvanlaenen** [filipvanlaenen/sharpen_pitest#9]
When a test class is missing, an error is currently thrown:

```
/home/fvl/bin/sharpen_pitest.rb:84:in `read': No such file or directory @ rb_sysopen - ../tsvgj-pit-reports/ArcToCommandTest//net.filipvanlaenen.tsvgj.internal/index.html (Errno::ENOENT)
	from /home/fvl/bin/sharpen_pitest.rb:84:in `block in <main>'
	from /home/fvl/bin/sharpen_pitest.rb:78:in `each'
	from /home/fvl/bin/sharpen_pitest.rb:78:in `<main>'
```

This should be caught and reported with an instruction how to continue.

**Comment by filipvanlaenen** [comment]
The instruction to continue should in this case be:

```
pitest ArcToCommandTest
```
